name: Tests Java + Rapport avec Surefire

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Exécuter les tests
        run: mvn clean test

      - name: Générer le rapport de test HTML
        run: mvn surefire-report:report-only

      - name: Uploader le rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tests
          path: target/site/
